# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='course',
        ),
    ]
