# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
