# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltreview', '0002_auto_20171214_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beltreview.user'),
            preserve_default=False,
        ),
    ]
