# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorite',
            field=models.IntegerField(default='0'),
        ),
    ]
